# Generated by Django 6.0.3 on 2026-04-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='guide_group_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
