# Generated by Django 6.0.3 on 2026-04-04 07:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideGroup',
            fields=[
                ('guide_group_id', models.AutoField(primary_key=True, serialize=False)),
                ('guide_groupname', models.CharField(max_length=100, unique=True)),
                ('guide_group_picture', models.ImageField(blank=True, null=True, upload_to='guide_groups/')),
                ('guide_group_number', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Guide Groups',
                'db_table': 'guide_groups',
            },
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('guide_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('national_id', models.CharField(max_length=50, unique=True)),
                ('phone_number', models.CharField(max_length=17)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('experience_years', models.IntegerField(default=0)),
                ('languages_spoken', models.CharField(help_text='Comma-separated languages', max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_tours', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guide_profile', to=settings.AUTH_USER_MODEL)),
                ('guide_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guides', to='guides.guidegroup')),
            ],
            options={
                'verbose_name_plural': 'Guides',
                'db_table': 'guides',
            },
        ),
        migrations.CreateModel(
            name='GuideGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(help_text='Position in group (1-8)')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='guides.guide')),
                ('guide_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='guides.guidegroup')),
            ],
            options={
                'db_table': 'guide_group_members',
                'ordering': ['index'],
                'unique_together': {('guide_group', 'guide')},
            },
        ),
    ]
