# Generated by Django 6.0.3 on 2026-04-04 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidegroup',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guidegroup',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guidegroup',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='guidegroup',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='guide',
            name='guide_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guides', to='guides.guidegroup'),
        ),
    ]
