# Generated by Django 6.0.3 on 2026-04-04 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
        ('guides', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('tour_id', models.AutoField(primary_key=True, serialize=False)),
                ('tour_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('total_seats', models.IntegerField(default=1)),
                ('available_seats', models.IntegerField(default=1)),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guide_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='guides.guidegroup')),
            ],
            options={
                'verbose_name_plural': 'Tours',
                'db_table': 'tours',
            },
        ),
        migrations.CreateModel(
            name='TourBooking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('number_of_travellers', models.IntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('payment_id', models.CharField(blank=True, max_length=100)),
                ('special_requests', models.TextField(blank=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tours.tour')),
                ('traveller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Tour Bookings',
                'db_table': 'tour_bookings',
            },
        ),
        migrations.CreateModel(
            name='TourDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('arrival_date', models.DateField()),
                ('departure_date', models.DateField()),
                ('arrival_time', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('stay_duration_hours', models.IntegerField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destinations.destination')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='tours.tour')),
            ],
            options={
                'db_table': 'tour_destinations',
                'ordering': ['order'],
                'unique_together': {('tour', 'order')},
            },
        ),
        migrations.CreateModel(
            name='FoodPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=20)),
                ('meal_description', models.TextField()),
                ('meal_items', models.TextField(help_text='Comma-separated meal items')),
                ('dietary_options', models.CharField(blank=True, max_length=200)),
                ('tour_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_plans', to='tours.tourdestination')),
            ],
            options={
                'db_table': 'food_plans',
                'unique_together': {('tour_destination', 'day_number', 'meal_type')},
            },
        ),
    ]
