# Generated by Django 6.0.3 on 2026-04-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_tour_cover_image_tourimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourbooking',
            name='guide_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
