# Generated by Django 6.0.3 on 2026-04-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_tourbooking_guide_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tour',
            name='total_expenses',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
