# Generated by Django 6.0.3 on 2026-04-05 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Trips'},
        ),
    ]
